### ISSUE TITLE
normalize css 교체예정

### ISSUE THREAD

**Issue by redgoose-dev** [redgoose-dev/slideshow#2]
소스가 더 적은방식이 있어 교체하려한다.

```css
/*** The new CSS Reset - version 1.0.0 (last updated 8.7.2021) ***/

/* Remove all the styles of the "User-Agent-Stylesheet", except for the 'display' property */
*:where(:not(iframe, canvas, img, svg, video):not(svg *)){
  all: unset;
  display: revert;
}

/* Preferred box-sizing value */
*,
*::before,
*::after{
  box-sizing: border-box;
}

/* Remove list styles (bullets/numbers) */
ol, ul {
  list-style: none;
}

/* For images to not be able to exceed their container */
img {
  max-width: 100%;
}

/* removes spacing between cells in tables */
table{
  border-collapse: collapse;
}
```

엄청많은 리셋을 시키기 때문에 점검이 꼭 필요한 부분이다.
